

services:
  tests:
    build:
      context: ..
      dockerfile: Dockerfile-test
    container_name: tests
    command: sh -c "python manage.py test"
    env_file:
      - ../.env 
    volumes:
      - ..:/app/